# Raw Data
data:
  # Path to the data file or directory
  path: ???

  # Data standard, one of (direct, meds, esgpt)
  standard: ???

  # Timestamp format for direct predicates (if meds or esgpt, this is ignored).
  ts_format: "%m/%d/%Y %H:%M"

# Cohort directory and name: used for automatically loading configs, saving results, and logging.
cohort_dir: ???
cohort_name: ???

# Path to the task configuration file
config_path: ${cohort_dir}/${cohort_name}.yaml

# Where the results are stored
output_filepath: ${cohort_dir}/${cohort_name}.parquet

# Hydra
hydra:
  job:
    name: ${cohort_name}_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: ${cohort_dir}/.logs/${hydra.job.name}
  sweep:
    dir: ${cohort_dir}/.logs/${hydra.job.name}

defaults:
  - override hydra/help: aces_help
